[formatting]
array_auto_collapse = false
indent_string = "    "
compact_arrays = false
column_width = 120
reorder_arrays = true

[[rule]]
include = [ "**/pyproject.toml" ]
keys = [ "dependency-groups", "project" ]

[rule.formatting]
reorder_arrays = false
