[formatting]
array_auto_collapse = false
column_width = 120
compact_arrays = false
indent_string = "    "
reorder_arrays = true
reorder_keys = true

[[rule]]
include = [ "**/pyproject.toml" ]
keys = [ "project", "tool.coverage" ]

[rule.formatting]
reorder_arrays = false

[[rule]]
include = [ "**/pyproject.toml" ]
keys = [
    "build-system",
    "dependency-groups",
    "project",
    "tool.coverage",
    "tool.mypy.overrides",
    "tool.pyproject2conda",
    "tool.uv",
]

[rule.formatting]
reorder_keys = false
