name: Update pre-commit hook versions
on:
  schedule:
    - cron: "0 6 * * 0,2,4" # Every sun, tues, thur at 6am utc
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    name: Bump versions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup-cached-uv-and-python
        with:
          python-version-file: ".python-version"
          cache-dependency-path: requirements/lock/uvx-tools.txt
      - uses: extractions/setup-just@e33e0265a09d6d736e2ee1e0eb685ef1de4669ff # v3.0.0

      - name: Update template pre-commit hooks
        run: just template-lint-upgrade
      - name: Update pre-commit hooks
        run: just lint-upgrade

      - name: Git config
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Create pull request
        id: cpr
        uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8.1.0
        with:
          token: ${{ secrets.PAT }}
          add-paths: .
          commit-message: "chore(deps): update template pre-commit hooks"
          title: "chore(deps): update template pre-commit hooks"
          labels: dependencies
          branch: prek/autoupdate
          delete-branch: true
          body: |
            This is an autogenerated PR. Use this to merge changes to this repository.

      - name: Pull request info
        if: ${{ steps.cpr.outputs.pull-request-number }}
        env:
          NUMBER: ${{ steps.cpr.outputs.pull-request-number }}
          URL: ${{ steps.cpr.outputs.pull-request-url }}
          OPERATION: ${{ steps.cpr.outputs.pull-request-operation }}
          SHA: ${{ steps.cpr.outputs.pull-request-sha }}
          BRANCH: ${{ steps.cpr.outputs.pull-request-branch }}
          VERIFIED: ${{ steps.cpr.outputs.pull-request-commits-verified }}
        run: |
          echo "Pull Request Number    - $NUMBER"
          echo "Pull Request URL       - $URL"
          echo "Pull Request Operation - $OPERATION"
          echo "Pull Request SHA       - $SHA"
          echo "Pull Request BRANCH    - $BRANCH"
          echo "Pull Request VERIFIED  - $VERIFIED"
