name: Update repository with copier
on:
  schedule:
    - cron: "0 2 * * 1" # Every Monday at 2am
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

env:
  COPIER_OPTIONS: "--trust -A -r main"

jobs:
  update:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - add-paths: .
            body: Use this to merge the changes to this repository.
            branch: copier/update
            commit-message: "chore: accept new copier update"
            title: New updates detected with copier
          - add-paths: .copier-answers.yml
            body: Use this to reject the changes in this repository.
            branch: copier/reject
            commit-message: "chore: reject new copier update"
            title: Reject new updates detected with copier
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: ./.github/actions/setup-cached-uv-and-python
        with:
          python-version-file: ".python-version"
          cache-dependency-path: requirements/lock/uvx-tools.txt
      - name: Install copier
        run:
          uv tool install -crequirements/lock/uvx-tools.txt --with
          copier-template-extensions copier
      - name: Copier update
        continue-on-error: false
        id: check
        run: |
          CHANGES=0
          if [ -f .copier-answers.yml ]; then
            copier update ${{ env.COPIER_OPTIONS }}
            if ! git diff --quiet -- .copier-answers.yml; then
              CHANGES=1
            fi
          else
            echo "No .copier-answers.yml file"
          fi

          echo "has_changes=$CHANGES" >> "$GITHUB_OUTPUT"

      - name: Git config
        if: steps.check.outputs.has_changes == '1'
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

          git restore --staged .

      - name: Create pull request
        if: steps.check.outputs.has_changes == '1'
        uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          add-paths: ${{ matrix.add-paths }}
          commit-message: ${{ matrix.commit-message }}
          branch: ${{ matrix.branch }}
          delete-branch: true
          branch-suffix: timestamp
          title: ${{ matrix.title }}
          body: |
            This is an autogenerated PR. ${{ matrix.body }}

            [copier](https://github.com/copier-org/copier) has detected updates from the Cookiecutter repository.
